fix pad of build

diff --git a/script/run b/script/run
--- a/script/run
+++ b/script/run
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 # Navigate to the build folder
-cd /home/dungdz/fpt-intern-zb-gw-unify/build || { echo "Build folder not found"; exit 1; }
+cd "$(dirname "$0")/../build" || { echo "Build folder not found"; exit 1; }
 
 # Check if zb-gw-unify exists and run it
 if [ -f zb-gw-unify ]; then
